from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 276)
        MainWindow.setMaximumSize(QtCore.QSize(590, 280))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 10, 531, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.everythingLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.everythingLayout.setContentsMargins(0, 0, 0, 0)
        self.everythingLayout.setSpacing(7)
        self.everythingLayout.setObjectName("everythingLayout")
        self.labelsLayout = QtWidgets.QHBoxLayout()
        self.labelsLayout.setSpacing(7)
        self.labelsLayout.setObjectName("labelsLayout")
        self.housesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.housesLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.housesLabel.setObjectName("housesLabel")
        self.labelsLayout.addWidget(self.housesLabel)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.labelsLayout.addWidget(self.line_3)
        self.usersLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.usersLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.usersLabel.setObjectName("usersLabel")
        self.labelsLayout.addWidget(self.usersLabel)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.labelsLayout.addWidget(self.line_4)
        self.HousingsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.HousingsLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.HousingsLabel.setObjectName("HousingsLabel")
        self.labelsLayout.addWidget(self.HousingsLabel)
        self.everythingLayout.addLayout(self.labelsLayout)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.everythingLayout.addWidget(self.line_5)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.housesLayout = QtWidgets.QVBoxLayout()
        self.housesLayout.setSpacing(15)
        self.housesLayout.setObjectName("housesLayout")
        self.addHouseButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.addHouseButton.setObjectName("addHouseButton")
        self.housesLayout.addWidget(self.addHouseButton)
        self.searchHouseButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.searchHouseButton.setObjectName("searchHouseButton")
        self.housesLayout.addWidget(self.searchHouseButton)
        self.buyHouseButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.buyHouseButton.setObjectName("buyHouseButton")
        self.housesLayout.addWidget(self.buyHouseButton)
        self.checkApprovalButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.checkApprovalButton.setObjectName("checkApprovalButton")
        self.housesLayout.addWidget(self.checkApprovalButton)
        self.buttonsLayout.addLayout(self.housesLayout)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.buttonsLayout.addWidget(self.line)
        self.usersLayout = QtWidgets.QVBoxLayout()
        self.usersLayout.setSpacing(10)
        self.usersLayout.setObjectName("usersLayout")
        self.addAdminButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.addAdminButton.setObjectName("addAdminButton")
        self.usersLayout.addWidget(self.addAdminButton)
        self.removeUserButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.removeUserButton.setObjectName("removeUserButton")
        self.usersLayout.addWidget(self.removeUserButton)
        self.buttonsLayout.addLayout(self.usersLayout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.buttonsLayout.addWidget(self.line_2)
        self.housingLayout = QtWidgets.QVBoxLayout()
        self.housingLayout.setObjectName("housingLayout")
        self.showHousingInfoButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.showHousingInfoButton.setObjectName("showHousingInfoButton")
        self.housingLayout.addWidget(self.showHousingInfoButton)
        self.buttonsLayout.addLayout(self.housingLayout)
        self.everythingLayout.addLayout(self.buttonsLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Saha Housings"))
        self.housesLabel.setText(_translate("MainWindow", "Houses Stuff"))
        self.usersLabel.setText(_translate("MainWindow", "Users Stuff"))
        self.HousingsLabel.setText(_translate("MainWindow", "Housing Stuff"))
        self.addHouseButton.setText(_translate("MainWindow", "Add House"))
        self.searchHouseButton.setText(_translate("MainWindow", "Search for Houses"))
        self.buyHouseButton.setText(_translate("MainWindow", "Buy House"))
        self.checkApprovalButton.setText(_translate("MainWindow", "Check Approval"))
        self.addAdminButton.setText(_translate("MainWindow", "Add Admin"))
        self.removeUserButton.setText(_translate("MainWindow", "Remove User"))
        self.showHousingInfoButton.setText(_translate("MainWindow", "Show Housing Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
